### ISSUE TITLE
LTCGI reflection

### ISSUE THREAD

**Issue by mecreeping** [koorimizuw/YamaPlayer#12]
The reflection casted by LTCGI is not inverted/flipped, its the same orientation as the player. I think this is due to the render texture being flipped to begin with. 

Also it would be a good feature if you could adjust the tiling and offset of the screen material without them being reset on runtime. 
I love the player though!

LTCGIによって投影される反射は反転しておらず、選手と同じ向きです。これは、そもそもレンダリングテクスチャが反転しているためだと思います。

また、スクリーン素材のタイリングとオフセットを、実行時にリセットされることなく調整できれば、良い機能だと思います。
でも、プレーヤーは大好きです！

**Comment by koorimizuw** [comment]
@mecreeping 
#14 で修正させていただきました。
引き続きよろしくお願いします。
