### ISSUE TITLE
Give instance Master the Admin permission

### ISSUE THREAD

**Issue by DrSakuu** [koorimizuw/YamaPlayer#13]
If the default permission is set to Viewer and instance owner is not in the instance, then nobody can operate the video player. There should be an optional checkbox to give the instance master the Admin permission. This would also solve Group instances with no owner.

デフォルトの権限がViewerに設定されていて、インスタンスオーナーがインスタンス内にいない場合は、誰もビデオプレーヤーを操作できません。インスタンスマスターにAdmin権限を付与するためのオプションのチェックボックスが必要です。これにより、オーナーがいないGroupインスタンスの問題も解決されます。

**Comment by koorimizuw** [comment]
@DrSakuu 
Thank you!!

https://github.com/koorimizuw/YamaPlayer/pull/14/commits/21bdfea8348009ddf8b1cdc90811bbecfd8a8bd1#diff-6c15afda348527f7a8e1fbe1cf309701b674b20051ea913e0999a174d36e370aR16-R30

I add options to grant owner permission to Instance owner or Instance master. It will release in next version(v1.4.11)
