### ISSUE TITLE
輝度（Brightness）の初期値について

### ISSUE THREAD

**Issue by Rikurus** [koorimizuw/YamaPlayer#18]
YamaPlayerの輝度の初期値が現在は"1"ですが、
白い部屋が映るような動画を視聴する際に白飛びが発生するため
"0"、または"0.5"辺りを初期値として設定していただくことは可能でしょうか。

**Comment by koorimizuw** [comment]
@Rikurus 
スクリーンの白飛び対策に、v1.4.11でライティング関連の初期値を調整しました。
v1.4.11以上のバージョンに更新してみてください。
