### ISSUE TITLE
"Urlを入力"のUrl表記の変更提案

### ISSUE THREAD

**Issue by kxn4t** [koorimizuw/YamaPlayer#25]
大交流会ではありがとうございました 🙇 
話した内容をIssueに上げさせてもらいます。

プレイヤー上の"Urlを入力"など、UI上の"Url"表記を"URL"に統一することを提案したいです。
これは単純に自分が気持ち悪いと感じる部分もあるんですが、URLはすべて大文字で表記するのが一般的だと思われます。

ちなみにURLが定義されたrfcにおいても、"URL"と大文字で統一されています。
https://datatracker.ietf.org/doc/html/rfc1738

検討よろしくお願いします 🙇

**Comment by koorimizuw** [comment]
@kxn4t 
昨日はありがとうございました！
https://github.com/koorimizuw/YamaPlayer/commit/62ce0b60e8639b5117bf7f20e6d2bb3ee5c0ef29
修正させていただきました、次のアップデートで反映されます！
