### ISSUE TITLE
v1.5以降でmacOSにてYouTube等からのプレイリストの取得に失敗する

### ISSUE THREAD

**Issue by hiyakake** [koorimizuw/YamaPlayer#29]
v1.5以降でmacOSにてYouTube等からのプレイリストの取得に失敗します。
1.4.xでは動作しておりました。

Unityのエラーから推測するに、1.5以降で利用・要求するyt-dlpがwindows用のexeファイルになっているようです。
Macではexeは動かせないため検証をお願いします。

**Comment by koorimizuw** [comment]
@hiyakake 
お世話になっております。
windows以外の環境もワールド作成できることは完全に失念しておりました。。

**Comment by koorimizuw** [comment]
@hiyakake 
developブランチで修正しました。
自分はmacosの環境がなくて申し訳ないですが、動作確認お願いしてもいいでしょうか。

**Comment by hiyakake** [comment]
確認したいのですがビルドの方法が分からず。。。
ベータ版としてリリースしてもらうことはできますか？

**Comment by koorimizuw** [comment]
@hiyakake 
ただいま`1.5.5-beta.1`をリリースしました、ご確認のほうお願いします。

**Comment by hiyakake** [comment]
![image](https://github.com/user-attachments/assets/305df943-b690-489c-a152-87bd405655ef)

試してみましたが、この通りエラーで実行できないですね。

**Comment by koorimizuw** [comment]
@hiyakake 
yt-dlpに権限が付与されてないのが原因みたいです、手動で付与したらいけると思いますが、コード側で対応しました。
`v1.5.5-beta.2`に更新してみてください。

**Comment by hiyakake** [comment]
@koorimizuw さん
試したところ、無事にプレイリストの取得ができました！
ありがとうございました！
